### ISSUE TITLE
Setting time in past near-instantly removes raid

### ISSUE THREAD

**Issue by ForcedUnknown** [ForcedUnknown/discord-bot#2]
Every minute the system checks for old raids to clean up, so if someone makes a mistake on setting the time, it's going to cause a lot of headaches for everyone.

We definitely should put some smarts into it, and make sure times are always set in the future, perhaps even restricting to a minimum of 10 minutes in the future to give people time to arrive?

**Comment by Googer** [comment]
Maybe instead of removing immediately-past raids it should really just be those that are a modest amount of time in the past (30 minutes to an hour)?  Is the cleanup going on the raid group's start time or the raid's end time?  If the latter, maybe even removing something like 10 minutes after that would be sufficient to balance cleaning out stale / no-longer-valid raids with avoiding an issue like this.

**Comment by ForcedUnknown** [comment]
@Googer it's based on End Time, then Start Time, and if neither exist, then it adds a configurable amount to the Creation Time and removes it then.  The problem though is they could always say something like 3pm, when they meant 6pm or something.  So you're always going to get scenarios where it's too far back to handle.

**Comment by Googer** [comment]
Hmmm.... maybe only do cleanup at the end of the day to truly remove raids that ended that day?  I don't know how often we intend on restarting the bot (but even if we do, we probably eventually want it persisting its state across restarts so it can recover from going down in the middle of the day, etc.).  Also notice I worded that in such a way that we could potentially have raids that don't end the same day (since it's always possible Mewtwo raids could even end up being a multiday thing; we just don't know how they'll work yet)

**Comment by ForcedUnknown** [comment]
Yes, mewtwo is the one I'm worried about, but I agree, I also want to put all this in a DB eventually so it persists even if the bot goes down for a moment.

**Comment by ForcedUnknown** [comment]
Can no longer set times in the past, though more user testing is likely needed
